"""
FLE-agent Web App — Flask backend.

Routes:
  GET  /            Home page (level/topic selector + newsletter form)
  POST /generate    Load exercise data from cache/
  GET  /exercise    Render exercise page
  GET  /download    Generate PDF in-memory and stream to browser
  POST /subscribe   Save newsletter subscriber to Supabase
"""

import io
import json
import os
import random
import re
import subprocess
import sys
from datetime import datetime

from dotenv import load_dotenv
from flask import (
    Flask,
    redirect,
    render_template,
    request,
    send_file,
    session,
    url_for,
)

load_dotenv()

app = Flask(__name__)
app.secret_key = os.getenv("FLASK_SECRET_KEY", "fle-agent-dev-secret-2026")

# ---------------------------------------------------------------------------
# Translations
# ---------------------------------------------------------------------------
TRANSLATIONS = {
    "fr": {
        "nav_home": "Accueil",
        "footer_text": "Généré par FLE-agent — French Language Exercise Automation",
        "hero_title": "Rencontrez votre tuteur de français - Il ne dort jamais",
        "hero_sub": "Propulsé par l'IA, votre agent s'adapte à votre niveau, <br>choisit les bons défis et vous maintient en apprentissage constant.",
        "generate_title": "Générer un exercice",
        "level_label": "Niveau CECRL",
        "topic_label": "Thème",
        "generate_btn": "Générer l'exercice →",
        "newsletter_title": "Recevoir les exercices par e-mail",
        "newsletter_sub": "Abonnez-vous pour recevoir un exercice PDF chaque semaine dans votre boîte de réception.",
        "name_label": "Prénom",
        "email_label": "Adresse e-mail",
        "name_placeholder": "Marie",
        "email_placeholder": "marie@exemple.fr",
        "subscribe_btn": "S'abonner gratuitement",
        "text_section": "📄 Texte",
        "source_label": "Source",
        "fun_fact_title": "Le saviez-vous ?",
        "download_pdf": "⬇ Télécharger le PDF",
        "questions_section": "❓ Questions de compréhension",
        "time_remaining": "Temps restant",
        "history_title": "📊 Mes résultats récents",
        "submit_btn": "Valider mes réponses",
        "restart_btn": "Recommencer",
        "vocab_section": "📚 Vocabulaire",
        "show_vocab": "Afficher le vocabulaire",
        "hide_vocab": "Masquer le vocabulaire",
        "vocab_word_col": "Mot / Expression",
        "vocab_def_col": "Définition &amp; Traduction",
        "word_count_label": "mots",
        "questions_count_label": "questions",
        "vocab_count_label": "mots de vocabulaire",
        "explanation_label": "Explication",
        "time_up": "Temps écoulé !",
        "msg_perfect": "Parfait ! Excellent travail ! 🎉",
        "msg_great": "Très bien ! Continuez comme ça ! 👏",
        "msg_good": "Bien joué ! Encore quelques efforts ! 💪",
        "msg_ok": "Pas mal ! Révisez le texte et réessayez. 📖",
        "msg_low": "Courage ! Lisez le texte attentivement et réessayez. 🔁",
        "progress_label": "{answered} / {total} répondu(es)",
    },
    "en": {
        "nav_home": "Home",
        "footer_text": "Generated by FLE-agent — French Language Exercise Automation",
        "hero_title": "Meet your French tutor - It never sleeps",
        "hero_sub": "Powered by AI, your agent adapts to your level, <br>picks the right challenges, and keeps you learning.",
        "generate_title": "Generate an exercise",
        "level_label": "CEFR Level",
        "topic_label": "Topic",
        "generate_btn": "Generate exercise →",
        "newsletter_title": "Receive exercises by email",
        "newsletter_sub": "Subscribe to receive a PDF exercise every week in your inbox.",
        "name_label": "First name",
        "email_label": "Email address",
        "name_placeholder": "Marie",
        "email_placeholder": "marie@example.com",
        "subscribe_btn": "Subscribe for free",
        "text_section": "📄 Text",
        "source_label": "Source",
        "fun_fact_title": "Did you know?",
        "download_pdf": "⬇ Download PDF",
        "questions_section": "❓ Comprehension questions",
        "time_remaining": "Time remaining",
        "history_title": "📊 My recent results",
        "submit_btn": "Submit answers",
        "restart_btn": "Restart",
        "vocab_section": "📚 Vocabulary",
        "show_vocab": "Show vocabulary",
        "hide_vocab": "Hide vocabulary",
        "vocab_word_col": "Word / Expression",
        "vocab_def_col": "Definition &amp; Translation",
        "word_count_label": "words",
        "questions_count_label": "questions",
        "vocab_count_label": "vocabulary words",
        "explanation_label": "Explanation",
        "time_up": "Time's up!",
        "msg_perfect": "Perfect! Excellent work! 🎉",
        "msg_great": "Very good! Keep it up! 👏",
        "msg_good": "Good job! A little more effort! 💪",
        "msg_ok": "Not bad! Review the text and try again. 📖",
        "msg_low": "Keep going! Read the text carefully and try again. 🔁",
        "progress_label": "{answered} / {total} answered",
    },
}

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
DEMO_MODE = os.getenv("DEMO_MODE", "true").lower() == "true"
BASE_DIR  = os.path.dirname(os.path.abspath(__file__))
CACHE_DIR = os.path.join(BASE_DIR, "cache")

TOPIC_DISPLAY = {
    "vie_quotidienne":      "Vie Quotidienne",
    "voyages_tourisme":     "Voyages & Tourisme",
    "environnement_ecologie": "Environnement & Écologie",
    "technologie_numerique": "Technologie & Numérique",
    "culture_histoire":     "Culture & Histoire",
}

TOPIC_ICONS = {
    "vie_quotidienne":       "🏠",
    "voyages_tourisme":      "✈️",
    "environnement_ecologie":"🌿",
    "technologie_numerique": "💻",
    "culture_histoire":      "🎨",
}

CULTURAL_FACTS = {
    "vie_quotidienne": [
        "En France, le déjeuner est souvent considéré comme le repas principal de la journée et peut durer plus d'une heure, même en semaine !",
        "Les Français consomment en moyenne 26 kg de fromage par personne et par an — le record mondial. Il existerait plus de 1 200 variétés de fromages français !",
        "La bise (se faire la bise) est une salutation courante en France, mais le nombre de bises varie selon les régions : 1 en Bretagne, 2 à Paris, jusqu'à 4 dans certaines régions du Sud.",
        "En France, les pharmacies sont identifiées par une croix verte lumineuse. Elles jouent un rôle important dans le système de santé : les pharmaciens peuvent donner des conseils médicaux de base.",
        "Le marché du dimanche est une tradition profondément ancrée dans la culture française. Même dans les petits villages, un marché hebdomadaire rassemble producteurs locaux et habitants.",
        "La France compte 11 jours fériés nationaux par an, dont le 14 juillet (Fête Nationale) qui commémore la prise de la Bastille en 1789.",
        "Les Français sont parmi les plus grands consommateurs de pain au monde : une baguette fraîche par jour et par foyer en moyenne !",
        "Le mot « café » désigne à la fois la boisson et le lieu. Un simple café au comptoir coûte généralement moins cher qu'une table en terrasse — une particularité typiquement française.",
        "En France, les enfants ont généralement deux heures de pause déjeuner à l'école, une tradition qui valorise le repas comme moment social important.",
        "La pétanque, jeu de boules très populaire, se joue dans presque tous les villages français. Elle est souvent associée à la convivialité du Sud de la France.",
    ],
    "voyages_tourisme": [
        "La France est le pays le plus visité au monde, accueillant plus de 89 millions de touristes chaque année. Paris seule reçoit plus de visiteurs que toute l'Australie !",
        "Le Mont-Saint-Michel, une abbaye perchée sur un rocher en Normandie, accueille environ 3 millions de visiteurs par an et est entouré par les marées deux fois par jour.",
        "La France possède 53 sites classés au patrimoine mondial de l'UNESCO — des châteaux de la Loire aux gorges du Verdon en passant par les arènes de Nîmes.",
        "Le Tour de France, la plus célèbre course cycliste au monde, traverse chaque été des dizaines de régions françaises et attire des millions de spectateurs sur le bord des routes.",
        "La Côte d'Azur (French Riviera) a été popularisée par des artistes comme Picasso et Matisse au début du XXe siècle. Elle reste l'une des destinations balnéaires les plus prisées d'Europe.",
        "Le château de Versailles, résidence royale construite par Louis XIV, possède 2 300 pièces et des jardins s'étendant sur 800 hectares. Il faudrait plusieurs jours pour tout visiter !",
        "La France est traversée par plus de 185 000 km de routes et chemins de randonnée, dont le célèbre GR 20 en Corse, considéré comme l'un des sentiers les plus difficiles d'Europe.",
        "Chaque année, des millions de pèlerins marchent le Chemin de Saint-Jacques-de-Compostelle qui traverse la France du Nord jusqu'aux Pyrénées, souvent plus de 1 500 km à pied.",
        "La ville de Lyon est classée au patrimoine mondial de l'UNESCO pour son ensemble architectural exceptionnel. Elle est aussi considérée comme la capitale mondiale de la gastronomie.",
        "Le viaduc de Millau, inauguré en 2004, est le pont routier le plus haut du monde avec un pilier culminant à 343 mètres — plus haut que la Tour Eiffel !",
    ],
    "environnement_ecologie": [
        "La France s'est engagée à atteindre la neutralité carbone d'ici 2050. Le pays possède déjà l'un des réseaux de transport ferroviaire à grande vitesse les plus étendus d'Europe.",
        "La forêt couvre environ 31 % du territoire français, soit 17 millions d'hectares. Cette superficie a doublé en moins de deux siècles grâce aux politiques de reboisement.",
        "La France produit environ 70 % de son électricité à partir du nucléaire, ce qui lui permet d'avoir l'un des taux d'émissions de CO₂ par habitant les plus bas d'Europe.",
        "Les Alpes françaises abritent le Mont-Blanc (4 808 m), le plus haut sommet d'Europe occidentale. Les glaciers alpins reculent cependant de plusieurs mètres chaque année à cause du réchauffement climatique.",
        "La Camargue, dans le delta du Rhône, est l'une des plus grandes zones humides d'Europe. Elle abrite des flamants roses sauvages et des chevaux blancs semi-sauvages emblématiques.",
        "La France compte 11 parcs nationaux qui protègent ses écosystèmes les plus fragiles, des Pyrénées aux Calanques de Marseille en passant par le parc des Écrins dans les Alpes.",
        "En France, la loi « anti-gaspillage » de 2020 interdit la destruction des invendus non alimentaires et oblige les grandes surfaces à donner leurs invendus alimentaires à des associations.",
        "La France abrite plus de 40 000 espèces animales et végétales. La biodiversité marine de l'Outre-mer français est parmi les plus riches du monde, notamment en Polynésie française.",
        "Les zones marines protégées françaises s'étendent sur plus de 23 % des eaux sous juridiction française, avec des objectifs d'atteindre 30 % d'ici 2030.",
        "Chaque année, le label « Vignobles & Découvertes » encourage un tourisme responsable dans les régions viticoles françaises, promouvant des pratiques agricoles durables et biologiques.",
    ],
    "technologie_numerique": [
        "La France est l'un des leaders mondiaux en intelligence artificielle, avec des startups comme Mistral AI. Paris est surnommée la « Station F », le plus grand campus de startups au monde.",
        "Le Minitel, ancêtre d'internet créé en France dans les années 1980, a été utilisé par des millions de Français pour consulter des informations et faire des réservations bien avant le World Wide Web.",
        "La France est le berceau du langage de programmation Caml/OCaml, toujours utilisé dans les universités du monde entier pour enseigner la programmation fonctionnelle.",
        "Criteo, BlaBlaCar, Deezer, Dailymotion et Doctolib sont parmi les licornes technologiques françaises les plus connues, faisant de la France un acteur majeur de l'écosystème tech européen.",
        "L'Inria (Institut national de recherche en informatique et en automatique) est l'un des centres de recherche en informatique les plus influents au monde, fondé en France en 1967.",
        "La France a été pionnière dans le déploiement de la 5G en Europe. En 2020, elle a lancé un plan de 100 milliards d'euros pour la relance économique, dont une part importante dédiée au numérique.",
        "Le jeu vidéo est une industrie majeure en France : Ubisoft, Gameloft et Focus Entertainment sont parmi les plus grands studios au monde, créant des franchises comme Assassin's Creed.",
        "La carte à puce (smart card) a été inventée par le Français Roland Moreno en 1974. Cette technologie est aujourd'hui utilisée dans des milliards de cartes bancaires et téléphoniques dans le monde.",
        "En France, le programme « French Tech » regroupe plus de 130 startups labellisées « licornes » ou « futures licornes », avec des levées de fonds record ces dernières années.",
        "La France investit massivement dans la cybersécurité : l'ANSSI (Agence nationale de la sécurité des systèmes d'information) est l'une des agences gouvernementales de cybersécurité les plus reconnues en Europe.",
    ],
    "culture_histoire": [
        "Le Louvre est le musée le plus visité au monde avec 9 millions de visiteurs par an. La Joconde (Mona Lisa) mesure seulement 77 × 53 cm — bien plus petite que la plupart des visiteurs ne l'imaginent !",
        "La Révolution française de 1789 a donné naissance à la devise nationale « Liberté, Égalité, Fraternité » et a inspiré des mouvements démocratiques dans le monde entier.",
        "La Tour Eiffel, construite en 1889 pour l'Exposition universelle, était initialement prévue pour être démolie. Elle est aujourd'hui le monument payant le plus visité au monde avec 7 millions de visiteurs par an.",
        "La langue française est parlée sur les 5 continents par environ 300 millions de personnes. C'est la 5e langue la plus parlée au monde et la 2e la plus étudiée.",
        "La France compte 20 lauréats du prix Nobel de littérature, le plus grand nombre pour un seul pays dans cette catégorie.",
        "Le cinéma a été inventé par les frères Lumière à Lyon en 1895. La France reste l'un des pays avec la plus grande production cinématographique d'Europe, et Cannes accueille le festival le plus prestigieux du monde.",
        "La bande dessinée (BD) est considérée comme le « 9e art » en France. Astérix, Tintin et Lucky Luke sont des personnages emblématiques traduits en plus de 100 langues.",
        "Versailles, la cathédrale Notre-Dame de Paris et le château de Chambord sont parmi les 45 000 monuments historiques protégés en France — le plus grand nombre en Europe.",
        "La gastronomie française a été inscrite au patrimoine culturel immatériel de l'UNESCO en 2010. Le repas gastronomique à la française est reconnu comme une pratique sociale et culturelle unique.",
        "Napoleon Bonaparte a codifié les lois françaises dans le « Code Napoléon » en 1804. Ce code juridique a influencé les systèmes légaux de plus de 40 pays dans le monde.",
    ],
}

def get_random_fact(topic: str) -> str:
    facts = CULTURAL_FACTS.get(topic, [])
    return random.choice(facts) if facts else ""

VALID_LEVELS = ["A1", "A2", "B1", "B2", "C1"]
VALID_TOPICS = list(TOPIC_DISPLAY.keys())

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_cached_exercise(level: str, topic: str) -> dict | None:
    """Load pre-built cache for a specific level+topic combination."""
    path = os.path.join(CACHE_DIR, f"{level}_{topic}.json")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def run_tools(level: str, topic: str) -> dict | None:
    """Call search + generate tools as subprocesses. Used in production mode."""
    python = sys.executable

    # Step 1: search
    result = subprocess.run(
        [python, "tools/search_french_text.py", "--level", level, "--topic", topic],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return None
    search = json.loads(result.stdout)

    # Step 2: generate exercises
    result = subprocess.run(
        [python, "tools/generate_exercises.py", "--level", level, "--topic", topic, "--text", search["text"]],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return None
    exercises = json.loads(result.stdout)

    return {**search, **exercises}


# ---------------------------------------------------------------------------
# i18n helpers
# ---------------------------------------------------------------------------

@app.context_processor
def inject_translations():
    lang = session.get("lang", "fr")
    return {"t": TRANSLATIONS[lang], "lang": lang}


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/set_lang")
def set_lang():
    lang = request.args.get("lang", "fr")
    if lang in TRANSLATIONS:
        session["lang"] = lang
    return redirect(request.referrer or url_for("index"))


@app.route("/")
def index():
    return render_template(
        "index.html",
        topics=TOPIC_DISPLAY,
        topic_icons=TOPIC_ICONS,
        levels=VALID_LEVELS,
    )


@app.route("/generate", methods=["POST"])
def generate():
    level = request.form.get("level", "").upper()
    topic = request.form.get("topic", "")

    if level not in VALID_LEVELS or topic not in VALID_TOPICS:
        return redirect(url_for("index"))

    # Always try the per-combination cache first
    data = load_cached_exercise(level, topic)
    if data is None:
        if DEMO_MODE:
            return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                                   levels=VALID_LEVELS,
                                   error=f"Cache introuvable pour {level} / {TOPIC_DISPLAY[topic]}. "
                                         f"Lancez d'abord : python tools/prebuild_cache.py")
        # Production fallback: generate on the fly
        data = run_tools(level, topic)
        if data is None:
            return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                                   levels=VALID_LEVELS, error="Erreur lors de la génération. Vérifiez les outils.")

    # Store only the key in session — full data is loaded from cache on the exercise page
    session["level"] = level
    session["topic"] = topic
    session["fun_fact"] = get_random_fact(topic)
    return redirect(url_for("exercise"))


@app.route("/exercise")
def exercise():
    level = session.get("level")
    topic = session.get("topic")
    if not level or not topic:
        return redirect(url_for("index"))
    data = load_cached_exercise(level, topic)
    if not data:
        return redirect(url_for("index"))
    data["topic_display"] = TOPIC_DISPLAY[topic]
    data["fun_fact"] = session.get("fun_fact", "")
    return render_template("exercise.html", data=data)


@app.route("/download")
def download():
    sys.path.insert(0, os.path.join(BASE_DIR, "tools"))
    from build_pdf import build_pdf_bytes  # noqa: PLC0415

    level = request.args.get("level") or session.get("level")
    topic = request.args.get("topic") or session.get("topic")

    if not level or not topic:
        return "Niveau ou thème manquant.", 400

    data = load_cached_exercise(level, topic)
    if not data:
        return "Données d'exercice introuvables.", 404

    exercises = {"questions": data.get("questions", []), "vocabulary": data.get("vocabulary", [])}
    try:
        pdf_bytes = build_pdf_bytes(
            level=level, topic=topic,
            text=data["text"], url=data["url"], site_name=data["site_name"],
            exercises=exercises,
        )
    except Exception as e:
        app.logger.error(f"PDF error: {e}")
        return "Erreur lors de la génération du PDF.", 500

    buf = io.BytesIO(pdf_bytes)
    buf.seek(0)
    return send_file(buf, as_attachment=True, mimetype="application/pdf",
                     download_name=f"exercise_{level}_{topic}.pdf")


@app.route("/subscribe", methods=["POST"])
def subscribe():
    name  = request.form.get("name", "").strip()
    email = request.form.get("email", "").strip().lower()

    if not name or not email:
        return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                               levels=VALID_LEVELS, sub_error="Veuillez remplir tous les champs.")

    if not re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email):
        return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                               levels=VALID_LEVELS, sub_error="Adresse e-mail invalide.")

    try:
        from supabase import create_client  # noqa: PLC0415
        sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_KEY"])
        if sb.table("subscribers").select("email").eq("email", email).execute().data:
            return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                                   levels=VALID_LEVELS, sub_error="Cette adresse est déjà inscrite.")
        sb.table("subscribers").insert({
            "name": name, "email": email,
            "subscribed_at": datetime.now().isoformat(),
        }).execute()
    except KeyError:
        app.logger.warning("Supabase env vars not set — subscriber not saved.")
    except Exception as e:
        app.logger.error(f"Supabase error: {e}")
        return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                               levels=VALID_LEVELS, sub_error="Erreur technique. Réessayez plus tard.")

    return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                           levels=VALID_LEVELS, sub_success=f"Merci {name} ! Vous êtes inscrit(e).")


if __name__ == "__main__":
    app.run(debug=True)
