"""
FLE-agent Web App — Flask backend.

Routes:
  GET  /            Home page (level/topic selector + newsletter form)
  POST /generate    Load exercise data from cache/
  GET  /exercise    Render exercise page
  GET  /download    Generate PDF in-memory and stream to browser
  POST /subscribe   Save newsletter subscriber to Supabase
  GET  /manage      Update subscriber preferences (level + topic)
  POST /manage      Save updated preferences to Supabase
  GET  /unsubscribe Remove subscriber from Supabase
  POST /admin/trigger-newsletter  Manually trigger the weekly newsletter
"""

import io
import json
import os
import random
import re
import subprocess
import sys
import uuid
from datetime import datetime

from dotenv import load_dotenv
from flask import (
    Flask,
    jsonify,
    redirect,
    render_template,
    request,
    send_file,
    session,
    url_for,
)

load_dotenv()

import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),        # No-ops cleanly if env var is absent
    integrations=[FlaskIntegration()],
    traces_sample_rate=0.0,             # Disable perf tracing (not needed)
    send_default_pii=False,
)

app = Flask(__name__)
app.secret_key = os.getenv("FLASK_SECRET_KEY")
if not app.secret_key:
    raise ValueError("FLASK_SECRET_KEY must be set in .env")

# ---------------------------------------------------------------------------
# Translations
# ---------------------------------------------------------------------------
TRANSLATIONS = {
    "fr": {
        "nav_home": "Accueil",
        "footer_text": "Généré par Évoli - FLE Agent",
        "hero_title": "Rencontrez Évoli - votre tuteur de français",
        "hero_sub": "Propulsé par l'IA, votre agent s'adapte à votre niveau, <br>choisit les bons défis et vous maintient en apprentissage constant.",
        "generate_title": "Générer un exercice",
        "level_label": "Niveau CECRL",
        "topic_label": "Thème",
        "generate_btn": "Générer l'exercice →",
        "newsletter_title": "Recevoir les exercices par e-mail",
        "newsletter_sub": "Abonnez-vous pour recevoir un exercice PDF chaque semaine dans votre boîte de réception.",
        "name_label": "Nom",
        "email_label": "Adresse e-mail",
        "name_placeholder": "Marie",
        "email_placeholder": "marie@exemple.fr",
        "subscribe_btn": "S'abonner gratuitement",
        "sub_level_label": "Niveau souhaité",
        "sub_topic_label": "Thème préféré",
        "sub_already": "Cet e-mail est déjà inscrit. Retrouvez le lien de gestion dans vos e-mails Évoli.",
        "text_section": "📄 Texte",
        "source_label": "Source",
        "fun_fact_title": "Le saviez-vous ?",
        "download_pdf": "⬇ Télécharger le PDF",
        "questions_section": "❓ Questions de compréhension",
        "time_remaining": "Temps restant",
        "history_title": "📊 Mes résultats récents",
        "submit_btn": "Valider mes réponses",
        "restart_btn": "Recommencer",
        "vocab_section": "📚 Vocabulaire",
        "show_vocab": "Afficher le vocabulaire",
        "hide_vocab": "Masquer le vocabulaire",
        "vocab_word_col": "Mot / Expression",
        "vocab_def_col": "Définition &amp; Traduction",
        "word_count_label": "mots",
        "questions_count_label": "questions",
        "vocab_count_label": "mots de vocabulaire",
        "explanation_label": "Explication",
        "time_up": "Temps écoulé !",
        "msg_perfect": "Parfait ! Excellent travail ! 🎉",
        "msg_great": "Très bien ! Continuez comme ça ! 👏",
        "msg_good": "Bien joué ! Encore quelques efforts ! 💪",
        "msg_ok": "Pas mal ! Révisez le texte et réessayez. 📖",
        "msg_low": "Courage ! Lisez le texte attentivement et réessayez. 🔁",
        "progress_label": "{answered} / {total} répondu(es)",
        "open_question_section": "✍️ Question ouverte",
    },
    "en": {
        "nav_home": "Home",
        "footer_text": "Generated by Évoli - FLE Agent",
        "hero_title": "Meet Évoli - your French tutor",
        "hero_sub": "Powered by AI, your agent adapts to your level, <br>picks the right challenges, and keeps you learning.",
        "generate_title": "Generate an exercise",
        "level_label": "CEFR Level",
        "topic_label": "Topic",
        "generate_btn": "Generate exercise →",
        "newsletter_title": "Receive exercises by email",
        "newsletter_sub": "Subscribe to receive a PDF exercise every week in your inbox.",
        "name_label": "Name",
        "email_label": "Email address",
        "name_placeholder": "Marie",
        "email_placeholder": "marie@example.com",
        "subscribe_btn": "Subscribe for free",
        "sub_level_label": "Preferred level",
        "sub_topic_label": "Preferred topic",
        "sub_already": "This email is already subscribed. Find the manage link in your Évoli emails.",
        "text_section": "📄 Text",
        "source_label": "Source",
        "fun_fact_title": "Did you know?",
        "download_pdf": "⬇ Download PDF",
        "questions_section": "❓ Comprehension questions",
        "time_remaining": "Time remaining",
        "history_title": "📊 My recent results",
        "submit_btn": "Submit answers",
        "restart_btn": "Restart",
        "vocab_section": "📚 Vocabulary",
        "show_vocab": "Show vocabulary",
        "hide_vocab": "Hide vocabulary",
        "vocab_word_col": "Word / Expression",
        "vocab_def_col": "Definition &amp; Translation",
        "word_count_label": "words",
        "questions_count_label": "questions",
        "vocab_count_label": "vocabulary words",
        "explanation_label": "Explanation",
        "time_up": "Time's up!",
        "msg_perfect": "Perfect! Excellent work! 🎉",
        "msg_great": "Very good! Keep it up! 👏",
        "msg_good": "Good job! A little more effort! 💪",
        "msg_ok": "Not bad! Review the text and try again. 📖",
        "msg_low": "Keep going! Read the text carefully and try again. 🔁",
        "progress_label": "{answered} / {total} answered",
        "open_question_section": "✍️ Open question",
    },
}

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
DEMO_MODE = os.getenv("DEMO_MODE", "true").lower() == "true"
BASE_DIR  = os.path.dirname(os.path.abspath(__file__))
BASE_URL  = os.getenv("BASE_URL", "http://localhost:5001").rstrip("/")
# Public URL used in emails — always points to the live site regardless of local BASE_URL
PUBLIC_URL = os.getenv("PUBLIC_URL", "https://fle-agent.onrender.com").rstrip("/")

TOPIC_DISPLAY = {
    "vie_quotidienne":        "Vie quotidienne & Société",
    "sante_bien_etre":        "Santé & Bien-être",
    "education_apprentissage": "Éducation & Apprentissage",
    "voyages_tourisme":       "Voyages & Mobilité",
    "environnement_ecologie": "Environnement & Écologie",
    "technologie_numerique":  "Technologies & Numérique",
    "culture_histoire":       "Culture, Arts & Histoire",
}

TOPIC_ICONS = {
    "vie_quotidienne":         "🏠",
    "sante_bien_etre":         "💚",
    "education_apprentissage": "🎓",
    "voyages_tourisme":        "✈️",
    "environnement_ecologie":  "🌿",
    "technologie_numerique":   "💻",
    "culture_histoire":        "🎨",
}

def get_random_fact(topic: str) -> str:
    try:
        sb = _get_supabase()
        rows = sb.table("fun_facts").select("fact").eq("topic", topic).execute().data
        return random.choice(rows)["fact"] if rows else ""
    except Exception:
        return ""

VALID_LEVELS = ["A1", "A2", "B1", "B2", "C1"]
VALID_TOPICS = list(TOPIC_DISPLAY.keys())

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_cached_exercise(level: str, topic: str) -> dict | None:
    """Load a random exercise for a specific level+topic from Supabase.

    Returns a randomly chosen row so users see different content on each visit
    as the exercise pool grows week over week.
    """
    try:
        sb = _get_supabase()
        rows = (
            sb.table("exercises")
            .select("*")
            .eq("level", level)
            .eq("topic", topic)
            .execute()
            .data
        )
        return random.choice(rows) if rows else None
    except Exception:
        return None


def fetch_exercise_ids(level: str, topic: str) -> list[str]:
    """Fetch all exercise IDs for a given level+topic (lightweight, IDs only)."""
    try:
        sb = _get_supabase()
        rows = (
            sb.table("exercises")
            .select("id")
            .eq("level", level)
            .eq("topic", topic)
            .execute()
            .data
        )
        return [row["id"] for row in rows] if rows else []
    except Exception:
        return []


def load_exercise_by_id(exercise_id: str) -> dict | None:
    """Fetch a single full exercise row by UUID."""
    try:
        sb = _get_supabase()
        rows = (
            sb.table("exercises")
            .select("*")
            .eq("id", exercise_id)
            .limit(1)
            .execute()
            .data
        )
        return rows[0] if rows else None
    except Exception:
        return None


def get_next_exercise_id(level: str, topic: str) -> str | None:
    """Return next exercise ID from the non-repeating shuffled queue.

    Session structure:
        session["lesson_queues"] = {
            "A1_vie_quotidienne": {"order": ["uuid1", ...], "index": 0}
        }
    - First call: fetches all IDs, shuffles once, stores order, returns first.
    - Subsequent calls: advances index circularly (wraps after exhaustion).
    """
    queue_key = f"{level}_{topic}"
    queues = session.get("lesson_queues", {})
    queue = queues.get(queue_key)

    if not queue:
        ids = fetch_exercise_ids(level, topic)
        if not ids:
            return None
        random.shuffle(ids)
        queue = {"order": ids, "index": 0}

    order = queue["order"]
    if not order:
        return None

    idx = queue["index"] % len(order)   # circular wrap
    exercise_id = order[idx]
    queue["index"] = idx + 1

    queues[queue_key] = queue
    session["lesson_queues"] = queues
    session.modified = True             # required for nested dict mutations
    return exercise_id


def load_latest_exercise(level: str, topic: str) -> dict | None:
    """Load the most recently generated exercise for a specific level+topic.

    Used by the newsletter to always send the freshest content from this week's batch.
    """
    try:
        sb = _get_supabase()
        rows = (
            sb.table("exercises")
            .select("*")
            .eq("level", level)
            .eq("topic", topic)
            .order("created_at", desc=True)
            .limit(1)
            .execute()
            .data
        )
        return rows[0] if rows else None
    except Exception:
        return None


def find_best_cached_exercise(level: str, topic: str) -> tuple:
    """Return the latest exercise for exact level+topic, or fall back to same topic any level.

    Used by the newsletter — always picks the most recently generated content.
    """
    data = load_latest_exercise(level, topic)
    if data:
        return data, level, topic
    # Fallback: same topic, any level (also pick latest)
    try:
        sb = _get_supabase()
        for lvl in VALID_LEVELS:
            rows = (
                sb.table("exercises")
                .select("*")
                .eq("level", lvl)
                .eq("topic", topic)
                .order("created_at", desc=True)
                .limit(1)
                .execute()
                .data
            )
            if rows:
                return rows[0], lvl, topic
        # Last resort: any exercise (latest overall)
        rows = (
            sb.table("exercises")
            .select("*")
            .order("created_at", desc=True)
            .limit(1)
            .execute()
            .data
        )
        if rows:
            r = rows[0]
            return r, r["level"], r["topic"]
    except Exception:
        pass
    return None, level, topic


def run_tools(level: str, topic: str) -> dict | None:
    """Call generate_lesson tool as subprocess. Used in production mode (non-demo, cache miss)."""
    python = sys.executable
    result = subprocess.run(
        [python, "tools/generate_lesson.py", "--level", level, "--topic", topic],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def _get_supabase():
    from supabase import create_client  # noqa: PLC0415
    return create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_KEY"])


def _track_usage(event_type: str, level: str = "", topic: str = "") -> None:
    """Fire-and-forget usage tracking write to Supabase.

    Runs in a background thread so it never adds latency to the HTTP response.
    Failures are logged as warnings but never raise to the caller.
    """
    import threading

    def _write():
        try:
            sb = _get_supabase()
            sb.table("usage_events").insert({
                "event_type": event_type,
                "level": level or None,
                "topic": topic or None,
            }).execute()
        except Exception as exc:
            app.logger.warning(f"Usage tracking write failed: {exc}")

    threading.Thread(target=_write, daemon=True).start()


def _subscriber_urls(token: str) -> tuple[str, str]:
    manage_url = f"{PUBLIC_URL}/manage?token={token}"
    unsubscribe_url = f"{PUBLIC_URL}/unsubscribe?token={token}"
    return manage_url, unsubscribe_url


# ---------------------------------------------------------------------------
# Newsletter job (triggered by GitHub Actions)
# ---------------------------------------------------------------------------

def send_newsletter_to_all() -> dict:
    """Fetch all subscribers and send each one a personalized exercise email."""
    sys.path.insert(0, os.path.join(BASE_DIR, "tools"))
    from build_pdf import build_pdf_bytes   # noqa: PLC0415
    from send_email import send as email_send  # noqa: PLC0415

    results = {"sent": [], "failed": [], "skipped": []}

    try:
        sb = _get_supabase()
        rows = sb.table("subscribers").select("name,email,level,topic,token").execute().data
    except Exception as e:
        app.logger.error(f"Newsletter: could not fetch subscribers: {e}")
        return {"error": str(e)}

    for row in rows:
        email   = row.get("email", "")
        name    = row.get("name", "")
        level   = row.get("level") or "A1"
        topic   = row.get("topic") or "vie_quotidienne"
        token   = row.get("token", "")

        data, actual_level, actual_topic = find_best_cached_exercise(level, topic)
        if not data:
            app.logger.warning(f"Newsletter: no cache found for {email} ({level}/{topic}) — skipping.")
            results["skipped"].append(email)
            continue

        try:
            pdf_bytes = build_pdf_bytes(
                level=actual_level, topic=actual_topic,
                text=data["text"], url=data.get("url", ""), site_name=data.get("site_name", ""),
                exercises={"questions": data.get("questions", []), "vocabulary": data.get("vocabulary", [])},
                open_question=data.get("open_question", ""),
            )
        except Exception as e:
            app.logger.error(f"Newsletter: PDF error for {email}: {e}")
            results["failed"].append(email)
            continue

        # Write to a temp file (send_email expects a file path)
        import tempfile
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp.write(pdf_bytes)
            tmp_path = tmp.name

        today = datetime.utcnow().strftime("%Y-%m-%d")
        desired_filename = f"exercice_{actual_level}_{actual_topic}_{today}.pdf"

        manage_url, unsubscribe_url = _subscriber_urls(token)
        result = email_send(
            pdf_path=tmp_path,
            level=actual_level,
            topic=actual_topic,
            source_url="",
            source_name="",
            recipient=email,
            manage_url=manage_url,
            unsubscribe_url=unsubscribe_url,
            recipient_name=name,
            pdf_filename=desired_filename,
        )
        os.unlink(tmp_path)

        if "error" in result:
            app.logger.error(f"Newsletter: send failed for {email}: {result}")
            results["failed"].append(email)
        else:
            results["sent"].append(email)

    app.logger.info(f"Newsletter done — sent: {len(results['sent'])}, "
                    f"failed: {len(results['failed'])}, skipped: {len(results['skipped'])}")
    return results


# ---------------------------------------------------------------------------
# i18n helpers
# ---------------------------------------------------------------------------

@app.context_processor
def inject_translations():
    lang = session.get("lang", "fr")
    return {"t": TRANSLATIONS[lang], "lang": lang}


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/set_lang")
def set_lang():
    lang = request.args.get("lang", "fr")
    if lang in TRANSLATIONS:
        session["lang"] = lang
    return redirect(request.referrer or url_for("index"))


@app.route("/")
def index():
    return render_template(
        "index.html",
        topics=TOPIC_DISPLAY,
        topic_icons=TOPIC_ICONS,
        levels=VALID_LEVELS,
    )


@app.route("/generate", methods=["POST"])
def generate():
    level = request.form.get("level", "").upper()
    topic = request.form.get("topic", "")

    if level not in VALID_LEVELS or topic not in VALID_TOPICS:
        return redirect(url_for("index"))

    _track_usage("generate", level=level, topic=topic)
    exercise_id = get_next_exercise_id(level, topic)

    if exercise_id is None:
        if DEMO_MODE:
            return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                                   levels=VALID_LEVELS,
                                   error=f"Cache introuvable pour {level} / {TOPIC_DISPLAY[topic]}. "
                                         f"Lancez d'abord : python tools/prebuild_cache.py")
        # Production fallback: generate on the fly
        data = run_tools(level, topic)
        if data is None:
            return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                                   levels=VALID_LEVELS, error="Erreur lors de la génération. Vérifiez les outils.")
        session["fallback_exercise"] = data
        session["current_exercise_id"] = None
    else:
        session["fallback_exercise"] = None
        session["current_exercise_id"] = exercise_id

    session["level"] = level
    session["topic"] = topic
    session["fun_fact"] = get_random_fact(topic)
    return redirect(url_for("exercise"))


@app.route("/exercise")
def exercise():
    level = session.get("level")
    topic = session.get("topic")
    if not level or not topic:
        return redirect(url_for("index"))
    exercise_id = session.get("current_exercise_id")
    if exercise_id:
        data = load_exercise_by_id(exercise_id)
    else:
        data = session.get("fallback_exercise")
    if not data:
        return redirect(url_for("index"))
    data["topic_display"] = TOPIC_DISPLAY[topic]
    data["fun_fact"] = session.get("fun_fact", "")
    return render_template("exercise.html", data=data)


@app.route("/download")
def download():
    sys.path.insert(0, os.path.join(BASE_DIR, "tools"))
    from build_pdf import build_pdf_bytes  # noqa: PLC0415

    level = request.args.get("level") or session.get("level")
    topic = request.args.get("topic") or session.get("topic")

    if not level or not topic:
        return "Niveau ou thème manquant.", 400

    exercise_id = session.get("current_exercise_id")
    if exercise_id:
        data = load_exercise_by_id(exercise_id)
    else:
        data = session.get("fallback_exercise")
    if not data:
        return "Données d'exercice introuvables.", 404

    exercises = {"questions": data.get("questions", []), "vocabulary": data.get("vocabulary", [])}
    try:
        pdf_bytes = build_pdf_bytes(
            level=level, topic=topic,
            text=data["text"], url=data.get("url", ""), site_name=data.get("site_name", ""),
            exercises=exercises,
            open_question=data.get("open_question", ""),
        )
    except Exception as e:
        app.logger.error(f"PDF error: {e}")
        return "Erreur lors de la génération du PDF.", 500

    buf = io.BytesIO(pdf_bytes)
    buf.seek(0)
    today = datetime.utcnow().strftime("%Y-%m-%d")
    return send_file(buf, as_attachment=True, mimetype="application/pdf",
                     download_name=f"exercice_{level}_{topic}_{today}.pdf")


@app.route("/subscribe", methods=["POST"])
def subscribe():
    name  = request.form.get("name", "").strip()
    email = request.form.get("email", "").strip().lower()
    level = request.form.get("sub_level", "A1").upper()
    topic = request.form.get("sub_topic", "vie_quotidienne")

    if level not in VALID_LEVELS:
        level = "A1"
    if topic not in VALID_TOPICS:
        topic = "vie_quotidienne"

    lang = session.get("lang", "fr")
    t = TRANSLATIONS[lang]

    def _render(sub_error=None, sub_success=None):
        return render_template("index.html", topics=TOPIC_DISPLAY, topic_icons=TOPIC_ICONS,
                               levels=VALID_LEVELS, sub_error=sub_error, sub_success=sub_success)

    if not name or not email:
        return _render(sub_error="Veuillez remplir tous les champs." if lang == "fr"
                       else "Please fill in all fields.")

    if not re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email):
        return _render(sub_error="Adresse e-mail invalide." if lang == "fr"
                       else "Invalid email address.")

    try:
        sb = _get_supabase()

        existing = sb.table("subscribers").select("email").eq("email", email).execute().data
        if existing:
            return _render(sub_error=t["sub_already"])

        token = str(uuid.uuid4())
        sb.table("subscribers").insert({
            "name": name,
            "email": email,
            "level": level,
            "topic": topic,
            "token": token,
            "subscribed_at": datetime.utcnow().isoformat(),
        }).execute()

    except KeyError:
        app.logger.warning("Supabase env vars not set — subscriber not saved.")
        token = ""
    except Exception as e:
        app.logger.error(f"Supabase error: {e}")
        return _render(sub_error="Erreur technique. Réessayez plus tard." if lang == "fr"
                       else "Technical error. Please try again later.")

    # Send welcome email in background — don't block the HTTP response
    if token:
        import threading
        sys.path.insert(0, os.path.join(BASE_DIR, "tools"))
        from send_email import send_welcome  # noqa: PLC0415
        manage_url, unsubscribe_url = _subscriber_urls(token)

        def _send_welcome_bg():
            try:
                result = send_welcome(
                    recipient=email, name=name, level=level, topic=topic,
                    manage_url=manage_url, unsubscribe_url=unsubscribe_url,
                )
                if "error" in result:
                    app.logger.warning(f"Welcome email failed: {result}")
                else:
                    app.logger.info(f"Welcome email sent to {email}")
            except Exception as e:
                app.logger.warning(f"Welcome email failed: {e}")

        threading.Thread(target=_send_welcome_bg, daemon=True).start()

    success_msg = (f"Merci {name} ! Vous êtes inscrit(e). Vérifiez votre boîte e-mail."
                   if lang == "fr" else
                   f"Thank you {name}! You're subscribed. Check your inbox.")
    return _render(sub_success=success_msg)


@app.route("/manage", methods=["GET", "POST"])
def manage():
    token = request.args.get("token", "")
    if not token:
        return redirect(url_for("index"))

    try:
        sb = _get_supabase()
        rows = sb.table("subscribers").select("name,level,topic").eq("token", token).execute().data
    except Exception:
        return redirect(url_for("index"))

    if not rows:
        return render_template("manage.html", error="Lien invalide ou expiré.",
                               topics=TOPIC_DISPLAY, levels=VALID_LEVELS, token=token)

    sub = rows[0]

    if request.method == "POST":
        new_level = request.form.get("level", sub["level"]).upper()
        new_topic = request.form.get("topic", sub["topic"])
        if new_level not in VALID_LEVELS:
            new_level = sub["level"]
        if new_topic not in VALID_TOPICS:
            new_topic = sub["topic"]
        try:
            sb.table("subscribers").update({"level": new_level, "topic": new_topic}).eq("token", token).execute()
            sub["level"] = new_level
            sub["topic"] = new_topic
            return render_template("manage.html", sub=sub, success=True,
                                   topics=TOPIC_DISPLAY, levels=VALID_LEVELS, token=token)
        except Exception as e:
            app.logger.error(f"Manage update error: {e}")
            return render_template("manage.html", sub=sub, error="Erreur technique.",
                                   topics=TOPIC_DISPLAY, levels=VALID_LEVELS, token=token)

    return render_template("manage.html", sub=sub,
                           topics=TOPIC_DISPLAY, levels=VALID_LEVELS, token=token)


@app.route("/unsubscribe", methods=["GET", "POST"])
def unsubscribe():
    token = request.args.get("token") or request.form.get("token", "")
    if not token:
        return redirect(url_for("index"))

    if request.method == "GET":
        # Show confirmation page — do NOT delete yet.
        # Email clients pre-fetch GET links, which would delete the row immediately.
        try:
            sb = _get_supabase()
            rows = sb.table("subscribers").select("name").eq("token", token).execute().data
            name = rows[0].get("name", "") if rows else ""
        except Exception:
            name = ""
        return render_template("manage.html", confirm_unsubscribe=True, name=name,
                               topics=TOPIC_DISPLAY, levels=VALID_LEVELS, token=token)

    # POST — user explicitly confirmed
    try:
        sb = _get_supabase()
        rows = sb.table("subscribers").select("name,email").eq("token", token).execute().data
        if rows:
            sb.table("subscribers").delete().eq("token", token).execute()
            name = rows[0].get("name", "")
            return render_template("manage.html", unsubscribed=True, name=name,
                                   topics=TOPIC_DISPLAY, levels=VALID_LEVELS, token=token)
    except Exception as e:
        app.logger.error(f"Unsubscribe error: {e}")

    return redirect(url_for("index"))


@app.route("/admin/trigger-newsletter", methods=["POST"])
def admin_trigger_newsletter():
    admin_token = os.getenv("ADMIN_TOKEN", "")
    provided = request.headers.get("X-Admin-Token", "")
    if not admin_token or provided != admin_token:
        return jsonify({"error": "unauthorized"}), 401

    results = send_newsletter_to_all()
    return jsonify(results)


@app.route("/health")
def health():
    """Render health check endpoint. Returns 200 while the app is alive."""
    return jsonify({"status": "ok"}), 200


@app.errorhandler(404)
def not_found(_e):
    return render_template("404.html"), 404


@app.errorhandler(500)
def server_error(_e):
    # Sentry already captured the exception via FlaskIntegration.
    return render_template("500.html"), 500


if __name__ == "__main__":
    app.run(debug=True, port=5001)
